/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.TelaCadastroConvidado;

import br.com.classe.Pessoa;
import javax.swing.JOptionPane;

/**
 *
 * @author Jean Heberth
 */
public class UITelaListaDeCadastroDeConvidado extends javax.swing.JFrame {

    Pessoa pessoa;
    Pessoa[] cadastraListaConvidado;
    int i = 0, qtdConvidados, campoVazio = 0;

    public UITelaListaDeCadastroDeConvidado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCampoNomeConvidado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbCampoSelecionaFraldas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCampoQuantidadeDePessoas = new javax.swing.JTextField();
        btnSalvarQuantidadeDePessoas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCampoQuantidadeDeFraldas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCampoMimo = new javax.swing.JTextArea();
        btnSalvarCadastro = new javax.swing.JButton();
        btnSairDoCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empresa J&E - Softwares");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de convidados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fraldas:");

        cmbCampoSelecionaFraldas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------", "Fraldas \" P \"", "Fraldas \" M \"", "Fraldas \" G \"" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Quantidade de pessoas:");

        txtCampoQuantidadeDePessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoQuantidadeDePessoasActionPerformed(evt);
            }
        });

        btnSalvarQuantidadeDePessoas.setText("Salvar");
        btnSalvarQuantidadeDePessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarQuantidadeDePessoasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Quantidade de fraldas:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mimo:");

        txtCampoMimo.setColumns(20);
        txtCampoMimo.setRows(5);
        jScrollPane1.setViewportView(txtCampoMimo);

        btnSalvarCadastro.setText("Salvar");
        btnSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroActionPerformed(evt);
            }
        });

        btnSairDoCadastro.setText("Sair");
        btnSairDoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairDoCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCampoQuantidadeDePessoas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCampoQuantidadeDeFraldas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCampoNomeConvidado)
                            .addComponent(cmbCampoSelecionaFraldas, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarQuantidadeDePessoas)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(btnSalvarCadastro)
                .addGap(62, 62, 62)
                .addComponent(btnSairDoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCampoQuantidadeDePessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarQuantidadeDePessoas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCampoNomeConvidado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbCampoSelecionaFraldas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCampoQuantidadeDeFraldas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastro)
                    .addComponent(btnSairDoCadastro))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1134, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarQuantidadeDePessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarQuantidadeDePessoasActionPerformed

        ValidarCampoQuantidadeDeConvidados();


    }//GEN-LAST:event_btnSalvarQuantidadeDePessoasActionPerformed

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed
        if (i < cadastraListaConvidado.length) {
            pessoa = new Pessoa();

            pessoa.setNome(txtCampoNomeConvidado.getName());
            if (txtCampoNomeConvidado.getText().equals("") || txtCampoQuantidadeDeFraldas.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha o campo corretamente!");
                txtCampoNomeConvidado.requestFocus();
                txtCampoQuantidadeDeFraldas.requestFocus();
            } else {
                cadastraListaConvidado[i] = pessoa;
                i++;
                qtdConvidados = cadastraListaConvidado.length - i;
                JOptionPane.showMessageDialog(null, "Convidado Cadastrado com sucesso!", "" + "Você pode cadastar mais: " + qtdConvidados + " Pessoa", JOptionPane.INFORMATION_MESSAGE);
                LimparCampos();
            }
        }

    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void btnSairDoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairDoCadastroActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairDoCadastroActionPerformed

    private void txtCampoQuantidadeDePessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoQuantidadeDePessoasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoQuantidadeDePessoasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UITelaListaDeCadastroDeConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UITelaListaDeCadastroDeConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UITelaListaDeCadastroDeConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UITelaListaDeCadastroDeConvidado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UITelaListaDeCadastroDeConvidado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSairDoCadastro;
    private javax.swing.JButton btnSalvarCadastro;
    private javax.swing.JButton btnSalvarQuantidadeDePessoas;
    private javax.swing.JComboBox<String> cmbCampoSelecionaFraldas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtCampoMimo;
    private javax.swing.JTextField txtCampoNomeConvidado;
    private javax.swing.JTextField txtCampoQuantidadeDeFraldas;
    private javax.swing.JTextField txtCampoQuantidadeDePessoas;
    // End of variables declaration//GEN-END:variables

    public void LimparCampos() {
        txtCampoQuantidadeDePessoas.setText("");
        txtCampoNomeConvidado.setText("");
        txtCampoQuantidadeDeFraldas.setText("");
        txtCampoMimo.setText("");
        cmbCampoSelecionaFraldas.setSelectedIndex(0);
    }

    public void ValidarCampoQuantidadeDeConvidados() {
        if (txtCampoQuantidadeDePessoas.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo corretamente!");
            txtCampoQuantidadeDePessoas.requestFocus();
        } else {
            cadastraListaConvidado = new Pessoa[Integer.parseInt(txtCampoQuantidadeDePessoas.getText())];
            JOptionPane.showMessageDialog(null, "Número de convidado cadastrado! "
                    + " Por favor digite os dados dos convidados");
            txtCampoNomeConvidado.requestFocus();
            txtCampoQuantidadeDePessoas.setText("");

        }
    }

//    public void ValidarCamposConvidado() {
//        if (txtCampoNomeConvidado.getText().equals("") && txtCampoQuantidadeDeFraldas.getText().equals("")) {
//            JOptionPane.showMessageDialog(null, "Por Favor preencha os campos corretamente!");
//            ValidarCamposConvidado();
//            
//        } else {
//            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
//        }
//
//    }
}
